# Generated by Django 4.0 on 2022-02-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง')], default='ชาย', max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('salary', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('birthday', models.DateField()),
                ('religion', models.CharField(choices=[('พุทธ', 'พุทธ'), ('ศริสต์', 'ศริสต์'), ('อิสลาม', 'อิสลาม'), ('อื่นๆ', 'อื่นๆ')], default='พุทธ', max_length=20)),
                ('addition_note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
